obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.3
cost_scaling_factor: 10.0

footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
inflation_radius: 0.3

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

map_type: costmap